# render.yaml - Render 部署設定
services:
  # Web 服務
  - type: web
    name: daigou-platform
    env: node
    region: singapore # 選擇新加坡區域，離台灣較近
    buildCommand: npm install
    startCommand: npm start
    plan: free # 使用免費方案，可升級為 starter 或 standard

    # 環境變數
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 3000

      - key: DATABASE_URL
        fromDatabase:
          name: daigou-db
          property: connectionString

      - key: SENDGRID_API_KEY
        sync: false # 需要在 Render Dashboard 手動設定

      - key: JWT_SECRET
        generateValue: true # 自動生成隨機值

      - key: SESSION_SECRET
        generateValue: true

    # 健康檢查
    healthCheckPath: /api/health

    # 自動部署設定
    autoDeploy: true # 當 GitHub 更新時自動部署

    # 靜態檔案
    staticPublishPath: ./frontend

# 資料庫服務
databases:
  - name: daigou-db
    plan: free # 使用免費 PostgreSQL
    region: singapore
    databaseName: daigou_platform
    user: daigou_admin

    # 資料庫版本
    version: "15"

    # IP 允許清單（可選）
    ipAllowList: [] # 空白表示允許所有 IP

# 定時任務（可選）
# crons:
#   - name: exchange-rate-updater
#     schedule: "0 */6 * * *"  # 每6小時執行一次
#     command: node scripts/update-exchange-rate.js
#
#   - name: daily-report
#     schedule: "0 9 * * *"  # 每天早上9點
#     command: node scripts/send-daily-report.js
